language: java

jdk:
- openjdk8

after_success:
- ./gradlew test jacocoTestReport coveralls
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    - COVERALLS_REPO_TOKEN=t4iMhDASBCpzSkXSXUwsyK043iITd1URA
    - CODECOV_TOKEN="36d5c69e-5a71-4a67-b0bf-59c262050d03"
