name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run cobertura coveralls
      run: ./gradlew cobertura coveralls
      env:
        super_secret: ${{ secrets.COVERALLS_REPO_TOKEN }}
